### ISSUE TITLE
Remove the 'Shooting game' from description.

### ISSUE THREAD

**Issue by NikkaGames** [Michel-M-code/Metadata-Decryptor#4]
remove (com.axlebolt.standoff2/Standoff2) from repo description or this repo might get suspended.

**Comment by LoftyCode** [comment]
It's a lie, you eat poop.

**Comment by NikkaGames** [comment]
a lie? they remove everything that's against their policy and game, I opened the issue for the good, to keep this repository alive.

**Comment by LoftyCode** [comment]
The repository is not working, they fixed it.

**Comment by NikkaGames** [comment]
welp, ok

**Comment by Michel-M-code** [comment]
Done. Thank you for the suggestion.
