### ISSUE TITLE
Error when dumping

### ISSUE THREAD

**Issue by ADAMOUMOU** [Michel-M-code/Metadata-Decryptor#5]
I get an error when dumping with the decrypted file with Perfare's il2cpp dumper:
System.ArgumentException: An item with the same key has already been added. Key: 1
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](TSource[] source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at Il2CppDumper.Metadata..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 102
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 124
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 98

**Comment by Michel-M-code** [comment]
Try a new version of the script. If it doesn't help, please tell me what version of which game you are trying to dump and from which version the reference global-metadata.dat file was.

**Comment by ADAMOUMOU** [comment]
Hello
I try to dump the latest version of critical ops with the reference file of the version 1.20 and 0.9.8. I tried with the update you did with both version (1.20 and then 0.9.8) and they don't work:
```bash
D:\cops\il2cpp>python MetadataDecryptor.py
Select mode. Automatic or Manual: a
Automatic mode selected.
Input encrypted metadata file path: D:\cops\il2cpp\global-metadata.dat
Input reference metadata file path: D:\cops\il2cpp\reference-global-metadata-1.20.dat
Input decrypted metadata save path: D:\cops\il2cpp\global-metadata.dat.dec
Using next files:
    Encrypted - D:\cops\il2cpp\global-metadata.dat
    Reference - D:\cops\il2cpp\reference-global-metadata-1.20.dat
    Output - D:\cops\il2cpp\global-metadata.dat.dec
Correct? yes
Enter 0 or 1
Correct? 1
Searching... : 100%|███████████████████████████████████████| 1922/1922 [00:01<00:00, 1284.28pairs/s]
Reordering...:   5%|██▊                                                | 69/1260 [00:00<?, ?pairs/s]
DECRYPTION FAILED!
Make sure you provided the right files, and if the decryption still fails, feel free to open an issue on my github: https://github.com/Michel-M-code/Metadata-Decryptor/issues/new

D:\cops\il2cpp>python MetadataDecryptor.py
Select mode. Automatic or Manual: a
Automatic mode selected.
Input encrypted metadata file path: new-global-metadata.dat
Input reference metadata file path: old-global-metadata-0.9.8.dat
Input decrypted metadata save path: global-metadata.dat
Using next files:
    Encrypted - new-global-metadata.dat
    Reference - old-global-metadata-0.9.8.dat
    Output - global-metadata.dat
Correct? 1
Searching... : 100%|███████████████████████████████████████| 1922/1922 [00:01<00:00, 1550.22pairs/s]
Reordering...:  13%|█████                                 | 168/1260 [00:00<00:00, 170657.08pairs/s]
DECRYPTION FAILED!
Make sure you provided the right files, and if the decryption still fails, feel free to open an issue on my github: https://github.com/Michel-M-code/Metadata-Decryptor/issues/new
```
Thanks for your response and sorry for the delay!

**Comment by Michel-M-code** [comment]
I'm currently working on a fix. Expect it to be released in near future.

**Comment by Michel-M-code** [comment]
After some further investigation i've come to the conclusion that the encryption method is different and I can't help you. Sorry for the delay.
