### ISSUE TITLE
idk whats wrong

### ISSUE THREAD

**Issue by WallD3v** [Michel-M-code/Metadata-Decryptor#6]
im running script by: py MetadataDecryptor.py --metadata global-metadata.dat --reference reference-global-metadata.dat --output decrypted-global-metadata.dat -a
(yes, im renamed script)

and gets:
line 104, in compare_bytes_at_offsets
    actual = struct.unpack("<b", metadata.read(1))[0]
struct.error: unpack requires a buffer of 1 bytes

**Comment by Michel-M-code** [comment]
Please upload the files that you specified in arguments.

**Comment by WallD3v** [comment]
[dump.zip](https://github.com/user-attachments/files/17602763/dump.zip)

**Comment by Michel-M-code** [comment]
Sorry, the script is not intended for this kind of encryption. The script is made to reorder values in the header, this is complete file encryption, so it won't work.
