### ISSUE TITLE
Encrypted metadata file is not a valid metadata file.

### ISSUE THREAD

**Issue by TouMobSiab** [Michel-M-code/Metadata-Decryptor#7]
Dumping Pixel Gun 3D. I managed to find a SteamDB without a encrypted GID or an actual Manifest ID.

![image](https://github.com/user-attachments/assets/a5ef6227-47de-453d-b319-8dedb72c7933)

In case you're wondering, they're using MFUSCATOR.dll, so I am not sure if this will help out.

**Comment by TouMobSiab** [comment]
For the reference, yes the first four bytes are this.
![image](https://github.com/user-attachments/assets/ae9672fe-67de-437e-ab88-805c606908d4)

**Comment by Michel-M-code** [comment]
sorry I'm not sure if I can help with that. The script also checks if the encrypted file is valid, and because it uses mfuscator that completely encrypts the metadata file, it is probably impossible to decrypt with my script.
